#Parameters that need to be changed depending on benchmark
IS_FLATTENED = true
TOP_MODULE 	= top
CLK_NAME 	= clock
RESET_NAME 	= reset
RESET_EDGE 	= 0
UNROLL_CYC	= 20
TARGET		= 335
OBJ_SRC 	= ./src/testcase.v

