#Parameters that need to be changed depending on benchmark
IS_FLATTENED = true
TOP_MODULE 	= b12
CLK_NAME 	= clock
RESET_NAME 	= reset
RESET_EDGE 	= 1
UNROLL_CYC	= 500
FUZZING_CYC = 500
STEP        = 1
TARGET		= 23
OBJ_SRC 	= ./src/b12.v

